### ISSUE TITLE
Removing vanilla's armor bar could cause compatibility issues

### ISSUE THREAD

**Issue by DomiIRL** [Andrew6rant/precise-armor#1]
Mods that change the armor bar rendering wouldn't work anymore. Maybe there is a solution with only modifying the size of the rendered sprite or smth and not replacing the entire rendering.

https://github.com/Andrew6rant/precise-armor/blob/308da92a46c70f297793332fd1530ba57ec57089/src/main/java/io/github/andrew6rant/precise_armor_bar/mixin/client/InGameHudMixin.java#L19

**Comment by Andrew6rant** [comment]
The solution I have made is to split Precise Armor Bar into two mods: Precise Armor, and Precise Armor Bar.

Precise Armor is the tiny one-mixin mod that actually changes damage calculations, and Precise Armor Bar is the optional mod that changes rendering. The code for Precise Armor can be found in the "api" branch: https://github.com/Andrew6rant/precise-armor/tree/api
